In [3]:
import requests #下載網頁
from bs4 import BeautifulSoup
url = r"https://zh.wikipedia.org/zh-tw/2026年电影"


In [17]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36"
}
resq = requests.get(url,headers=headers)
resq.encoding="utf-8"
#print(resq.text)
soup = BeautifulSoup(resq.text,"html5lib")
movieTable = soup.find("table",class_="wikitable sortable")
tbody = movieTable.find("tbody")
trList = tbody.find_all("tr")
for inx in  range(1,len(trList)):
    print("排名:",trList[inx].find("th").text,end="")
    print("片名:",trList[inx].select_one("a").text)
    print("全球票房",trList[inx].find_all("td")[-1].text)

排名: 1
片名: 超級瑪利歐銀河電影版
全球票房 $1,000,743,990[1]

排名: 2
片名: 麥可·傑克森
全球票房 $890,814,075[2]

排名: 3
片名: 極限返航
全球票房 $680,288,291[3]

排名: 4
片名: 穿著Prada的惡魔2
全球票房 $664,415,101[4]

排名: 5
片名: 飛馳人生3
全球票房 $656,459,523[5]

排名: 6
片名: 狸想世界
全球票房 $388,402,731[6][7]

排名: 7
片名: 曼達洛人與古古
全球票房 $296,182,333[8]

排名: 8
片名: 給阿嬤的情書
全球票房 $246,580,000[9]

排名: 9
片名: 咆哮山莊
全球票房 $241,701,072[10]

排名: 10
片名: 愛你致死不渝
全球票房 $234,501,640[11][12]



## Numpy
+ 可做到的功能
  + 快速的多維陣列操作。
  + 可靠的科學功能函數庫。
  + 可協助繪圖工具進行繪圖。
+ NumPy 是幾乎每個科學 Python 應用程序或模組的核心，它提供了以向量化形式的快速 N-d 陣列類型可供操作。

In [20]:
import numpy as np
a = [1,2,3,5,7,9]
b = [3,5,3,6,7,9]
print(type(a))
c = a + b
print(c)
np1 = np.array(a)
np2 = np.array(b)
print(type(np1))
print(type(np2))
print(np1 + np2)

<class 'list'>
[1, 2, 3, 5, 7, 9, 3, 5, 3, 6, 7, 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 4  7  6 11 14 18]


In [27]:
import numpy as np
i = [[1,2,3],
     [6,7,8]]#2x3矩陣
a = np.array(i)
print(a.ndim)
print(a.shape)
print(a.shape[0])
print(a.shape[1])
print(a.size)
print(a.dtype)

2
(2, 3)
2
3
6
int64


In [44]:
import numpy as np
i = [["1",2.3,3],
     [6,7,8]]#所有類型必須相同 字串 浮點 整數
a = np.array(i)
print(a.dtype)
print(a)

<U32
[['1' '2.3' '3']
 ['6' '7' '8']]


In [47]:
import numpy as np
i = [[1,2,3],
     [6,7,8]]#2x3矩陣
a = np.array(i,dtype=np.int8)
print(a)
print(a.dtype)

[[1. 2. 3.]
 [6. 7. 8.]]
float16


In [51]:
import numpy as np
a = np.array([6,7,8,9])
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)
d = b ** 2
print(d)


[6 7 8 9]
[0 1 2 3]
[6 6 6 6]
[0 1 4 9]


In [55]:
import numpy as np
f = np.array([5,-1,3,9,0])
print(f <= 3)
boolA = f <= 3
print(type(boolA))
print(f[boolA])
f[boolA] = 1
print(f)

[False  True  True False  True]
<class 'numpy.ndarray'>
[-1  3  0]
[5 1 1 9 1]


In [60]:
import numpy as np
x = np.empty((2,4))
print(x)
print("==============================")
x = np.zeros((2,4))
print(x)

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [69]:
import numpy as np
x = np.ones((2,4))
print(x)
print("=======================")
x = np.full((2,4),1)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]]


In [71]:
import numpy as np
x = np.eye(3)
print(x)
x = np.diag([1,2,3,4])
print(x)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### linspace arange

In [73]:
import numpy as np
x = np.linspace(2,10,6)#包含10
print(x)
print("======================")

[ 2.   3.6  5.2  6.8  8.4 10. ]


In [74]:
import numpy as np
x = np.arange(2,10)#不包含10
print(x)

[2 3 4 5 6 7 8 9]


In [82]:
import numpy as np
x = np.arange(2,12,1.5)#可小數點
print(x)

[ 2.   3.5  5.   6.5  8.   9.5 11. ]


In [92]:
import numpy as np
x = np.arange(8)
print(x)
print(x.shape)
newShape = x.reshape((2,4))
print(newShape)
newShape = x.reshape((4,2))
print(newShape)
newShape = x.reshape((8,1))
print(newShape)

[0 1 2 3 4 5 6 7]
(8,)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [95]:
#[25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]
import numpy as np
r1 = np.arange(25,30,.5)
print(r1)

[25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [96]:
#[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]
lin = np.linspace(3,5,9) # 5 -3 / 8
print(lin)

[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [101]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[0])
print(a[2][1])
print(a[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
8
8


In [103]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[1,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]


In [106]:
print(a[:,1])
a[1,2] = 75
print(a)

[2 5 8]
[[ 1  2  3]
 [ 4  5 75]
 [ 7  8  9]]


In [107]:
a[:,0] = [100,101,102]
print(a)

[[100   2   3]
 [101   5  75]
 [102   8   9]]


In [114]:
import numpy as np
a = np.arange(0,36).reshape((6,6))
print(a)
print("1==============")
#[3 4]
print(a[0,3:5])
'''
[[28 29]
 [34 35]]
'''
print("2==============")
print(a[4:,4:])
'''
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
'''
print("3==============")
print(a[:3,:3])
'''
[ 2  8 14 20 26 32]
'''
print("4==============")
print(a[:,2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
1==============
[3 4]
2==============
[[28 29]
 [34 35]]
3==============
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
4==============
[ 2  8 14 20 26 32]


## 重設新陣列
+ resize 這個動作會依據原本的陣列再設定指定大小的新陣列。 
+ resize 動作的參數如下：
+ numpy.resize(arr1，shape1)
  + arr1：原本的陣列
  + shape1：新規劃的大小
+ 如果規劃的新陣列比較大，將會重新複製原有陣列的資料，填滿新的儲存格。
+ resize 這個動作***建立新的陣列***，而 reshape 則是依據原有的重新規劃，仍會受到原有陣列影響。
+ transpose()轉置

In [120]:
import numpy as np
a = np.array([[1,2,3],
             [4,5,6]])
print(a.shape)
print(a)
b = a.reshape((1,6)) #共用資料
print(b)
print(b.shape)
b[0,0] = 999
print(b)
print("=======================")
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
(1, 6)
[[999   2   3   4   5   6]]
[[999   2   3]
 [  4   5   6]]


In [125]:
import numpy as np
a = np.array([[1,2,3],
             [4,5,6]])
print(a.shape)
print(a)
print("="*20)
b = np.resize(a,(3,2))#不會複製
print(b)
print(b.shape)
b[0,0] = 990
print("="*20)
print(b)
print("="*20)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[990   2]
 [  3   4]
 [  5   6]]
[[1 2 3]
 [4 5 6]]


In [128]:
import numpy as np
a = np.array([[1,2,3],
             [4,5,6]])
print(a.shape)
print(a)
b = np.resize(a,(10,10))
print(b)

(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4]
 [5 6 1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4 5 6]
 [1 2 3 4 5 6 1 2 3 4]]


### transpose

In [131]:
import numpy as np
newArray =  np.arange(10).reshape(2,5)
print("====================")
print(newArray)
print("====================")
print(newArray.transpose())
print("====================")
print(newArray.T)
print("====================")
tArray = newArray.T
tArray[1] = 9999
print(newArray)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[   0 9999    2    3    4]
 [   5 9999    7    8    9]]


In [132]:
import os
print(os.getcwd())

C:\Users\xvpow\ai_20260426\ch8


In [136]:
import numpy as np
x = np.loadtxt("data1.csv",skiprows=1,delimiter=",")
print(x)
print(type(x))

[[0.4 0.3]
 [0.1 0.6]
 [0.1 0.3]
 [0.5 0.3]]
<class 'numpy.ndarray'>


In [137]:
y,z = np.loadtxt("data1.csv",skiprows=1,delimiter=",",unpack=True)
print("v1:",y)
print("v2:",z)


v1: [0.4 0.1 0.1 0.5]
v2: [0.3 0.6 0.3 0.3]


import numpy as np
x = np.loadtxt("data2.csv",delimiter=",")

In [139]:
import numpy as np
a = np.genfromtxt("data2.csv",delimiter=",")
print(a)

[[0.2 0.1]
 [0.4 nan]
 [0.1 0.6]
 [0.1 0.3]
 [nan 0.3]]


## 總和最大與最小
+ np.sum( ) 代表某一個陣列內容的總和，也可以指定這個陣列的哪一軸 (axis) 內容總和。
+ np.min( ) 代表某一個陣列內容的最小值，也可以指定這個陣列的哪一軸 (axis) 內容的最小值。
+ np.max( ) 代表某一個陣列內容的最大值，也可以指定這個陣列的哪一軸 (axis) 內容的最大值。
+ amin 與 min 是相同功能的方法。
+ amax 與 max 是相同功能的方法。

In [144]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
print("=======================")
b = np.sum(a)
print(b)
b = np.sum(a,axis=0)
print(b)
b =  np.sum(a,axis=1)
print(b)

[[ 0 30 45]
 [60 75 90]]
300
[ 60 105 135]
[ 75 225]


In [148]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
print(a.shape)
t = a.shape
print(t[0])
print(t[1])
a1 = np.array([0,30,45])
a2 = np.array([60,75,90])
ans = a1 + a2
print(ans)

[[ 0 30 45]
 [60 75 90]]
(2, 3)
2
3
[ 60 105 135]


### max() min()

In [152]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
b = np.max(a)
print(b)
b = np.max(a,axis=0)
print(b)
b = np.max(a,axis=1)
print(b)

[[ 0 30 45]
 [60 75 90]]
90
[60 75 90]
[45 90]


In [155]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
bi = np.argmax(a)
print(bi)
bi = np.argmax(a,axis=0)
print(bi)
bi = np.argmax(a,axis=1)
print(bi)

[[ 0 30 45]
 [60 75 90]]
5
[1 1 1]
[2 2]


In [158]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
b = np.mean(a)
print(b)
b = np.mean(a,axis=0)
print(b)
b = np.mean(a,axis=1)
print(b)

[[ 0 30 45]
 [60 75 90]]
50.0
[30.  52.5 67.5]
[25. 75.]


In [165]:
import numpy as np
a = np.array([1,2,3,4])
b = np.average(a)
print(b)
wts = np.array([4,3,2,1])
b = np.average(a,weights=wts)#(1*4+2*3+3*2+4*1)/(4+3+2+1)
print(b)
b = np.average([1,2,3,4],weights=[4,3,2,1],returned=True)
print(b)

2.5
2.0
(np.float64(2.0), np.float64(10.0))


In [168]:
import numpy as np
a = np.array([[0,30,45],
              [60,75,90]])
print(a)
b = np.median(a)#(45+60)/2
print(b)
b = np.median(a,axis = 0)
print(b)
b = np.median(a,axis =1)
print(b)

[[ 0 30 45]
 [60 75 90]]
52.5
[30.  52.5 67.5]
[30. 75.]


## 作業
## 請計算出 106 與 107 年每個月 0 到 9歲國小(含)之前的人數總計